export const ADD_DATA = 'ADD_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'

export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_INVENTORIES_SUCCESS = 'LOAD_INVENTORIES_SUCCESS'
export const LOAD_INVENTORIES_FAILURE = 'LOAD_INVENTORIES_FAILURE'
export const ADD_INVENTORIES_SUCCESS = 'ADD_INVENTORIES_SUCCESS'
export const ADD_INVENTORIES_FAILURE = 'ADD_INVENTORIES_FAILURE'
