export const ADD_DATA = 'ADD_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'

export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_ITEMS_FAILURE = 'LOAD_ITEMS_FAILURE'
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS'


export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'
